#!/usr/bin/env python3
# =============================================================================
# indegree_convergence_generate.py   (STEP 1 of 2)
# -----------------------------------------------------------------------------
# Connectivity-ONLY Monte-Carlo generator for the in-degree convergence study.
#
# Goal
# ----
# We do NOT simulate any neuronal dynamics here. We only build the spatial wiring
# graph and record, for every neuron, its IN-DEGREE k (number of presynaptic
# partners), under a distance-dependent Weibull / stretched-exponential kernel:
#
#       p(d) = p0 * exp( -(d / d0)^beta )                       [d in micrometres]
#
# The scientific question (answered by the STEP-2 analysis script) is:
#   "For a given (d0, beta, p0) and a fixed neuronal density rho, is the
#    in-degree distribution P(k) independent of the culture size L?  If so,
#    above which minimum L* does it stabilise?"
# The mean in-degree converges as L grows iff the 2-D degree integral
#       <k> = 2*pi*rho * Integral_0^R p(d) * d  dd
# converges, i.e. iff the integrand p(d)*d has finite tail area. For the
# stretched exponential this holds for EVERY beta > 0, but the *length scale*
# of convergence grows quickly as beta -> 0, so small-beta kernels are expected
# to remain L-dependent across any feasible culture size.
#
# Boundaries (BOTH are generated by default)
# -------------------------------------------
#   'finite'   : ordinary Euclidean distance on the open square [0, L]^2.
#                Edge neurons have fewer reachable partners (degree gradient).
#   'periodic' : flat torus (opposite edges identified, NO twist => torus, not
#                a sphere), via the MINIMUM-IMAGE convention:
#                      Δx <- Δx - L*round(Δx/L),  Δy <- Δy - L*round(Δy/L)
#                so every neuron sees a full, identical neighbourhood and there
#                is no boundary gradient. The minimum-image convention caps the
#                largest possible separation at the half-diagonal L/sqrt(2);
#                this is the standard PBC convention (the same one a Brian2 PBC
#                model would use). The finite and periodic runs of a given
#                (L, rep) share the SAME point set, isolating the boundary effect.
#
# Graph model
# -----------
# Directed graph. Each ORDERED pair (i -> j), i != j, is an independent Bernoulli
# with probability  P(i->j) = p0 * exp(-(d_ij / d0)^beta),  where d_ij is the
# Euclidean distance ('finite') or the minimum-image distance ('periodic').
# in_degree[j] = # of presynaptic sources i. No autapses.
#
# Parallelism & restartability (HPC)
# -----------------------------------
# The grid is embarrassingly parallel. One TASK = one (boundary, L, repetition);
# inside a task the full (d0 x beta x p0) sub-grid is computed, reusing the
# pairwise-distance work across all kernel parameters. Tasks are distributed over
# CPU cores with a ProcessPoolExecutor (defaults to all cores the job is pinned
# to). Each finished task is written ATOMICALLY to its own .npz; a task whose
# output already exists is skipped, so a killed job resumes cleanly.
#
# Multi-node scaling: launch the same script as a PBS/Slurm array, passing
# --shard <index> --n_shards <total>; each array element processes a disjoint
# slice of the task list and still multiprocesses across its node's cores.
#
# Output (one file per task):  net_<boundary>_L<Lum>_rep<r>.npz
#   indegrees : int32 array, shape (n_d0, n_beta, n_p0, N)   <-- the raw data
#   d0_list, beta_list, p0_list, L_um, rho_per_mm2, rep, N, boundary, master_seed
# =============================================================================

from __future__ import annotations

import argparse
import json
import os
import time
from concurrent.futures import ProcessPoolExecutor, as_completed

import numpy as np


# -----------------------------------------------------------------------------
# Geometry / kernel helpers (pure numpy, importable by the analysis script & tests)
# -----------------------------------------------------------------------------
def n_neurons(L_um: float, rho_per_mm2: float) -> int:
    """Deterministic neuron count N = round(rho * area). L in um, rho in 1/mm^2."""
    area_mm2 = (L_um / 1000.0) ** 2
    return int(round(rho_per_mm2 * area_mm2))


def sample_positions(N: int, L_um: float, seedseq: np.random.SeedSequence) -> np.ndarray:
    """N uniform points in [0, L]^2 (um). Positions depend on (L, rep) only, so the
    'finite' and 'periodic' runs of the same (L, rep) share the SAME point set,
    isolating the boundary effect."""
    rng = np.random.default_rng(seedseq)
    return rng.uniform(0.0, L_um, size=(N, 2)).astype(np.float64)


def minimum_image_delta(delta: np.ndarray, L_um: float) -> np.ndarray:
    """Wrap coordinate differences to the nearest periodic image (flat torus)."""
    return delta - L_um * np.round(delta / L_um)


# -----------------------------------------------------------------------------
# Per-task computation
# -----------------------------------------------------------------------------
def compute_task(task, cfg):
    """Compute the (n_d0, n_beta, n_p0, N) in-degree tensor for one (boundary, L, rep)."""
    boundary, L_idx, L_um, rep = task

    d0_list   = np.asarray(cfg["d0_list"],   dtype=np.float64)
    beta_list = np.asarray(cfg["beta_list"], dtype=np.float64)
    p0_list   = np.asarray(cfg["p0_list"],   dtype=np.float64)
    n_d0, n_beta, n_p0 = len(d0_list), len(beta_list), len(p0_list)

    rho    = cfg["rho_per_mm2"]
    chunk  = cfg["chunk"]
    master = cfg["master_seed"]
    boundary_id = 0 if boundary == "finite" else 1

    N = n_neurons(L_um, rho)
    if N < 2:
        raise ValueError(f"L={L_um} um at rho={rho}/mm^2 gives N={N} (<2). Increase L.")

    # Positions shared across boundary types for this (L, rep).
    pos = sample_positions(N, L_um,
                           np.random.SeedSequence(entropy=master, spawn_key=(L_idx, rep)))
    px, py = pos[:, 0], pos[:, 1]

    indeg = np.zeros((n_d0, n_beta, n_p0, N), dtype=np.int32)

    # Chunk over POST neurons j; summing connections over PRE neurons i gives the
    # in-degree of each j directly. The distance matrix is computed ONCE per block
    # and reused across the whole (d0, beta, p0) grid.
    for c0 in range(0, N, chunk):
        c1 = min(c0 + chunk, N)
        jb = np.arange(c0, c1)                       # global post indices in this block
        B = c1 - c0

        dx = px[jb][:, None] - px[None, :]           # (B, N)  Δx for every (post, pre)
        dy = py[jb][:, None] - py[None, :]           # (B, N)
        if boundary == "periodic":                   # minimum-image wrap
            dx = minimum_image_delta(dx, L_um)
            dy = minimum_image_delta(dy, L_um)
        d = np.sqrt(dx * dx + dy * dy)               # Euclidean or minimum-image distance

        self_rows = np.arange(B)                     # mask self pairs (post == pre)
        self_cols = jb

        for a, d0 in enumerate(d0_list):
            for b, beta in enumerate(beta_list):
                base = np.exp(-((d / d0) ** beta))   # K_ij in [0,1], p0-independent
                base[self_rows, self_cols] = 0.0     # no autapse
                for q, p0 in enumerate(p0_list):
                    P = p0 * base                    # <= 1 since p0<=1, base<=1
                    ss = np.random.SeedSequence(
                        entropy=master,
                        spawn_key=(boundary_id, L_idx, rep, a, b, q, c0))
                    draws = np.random.default_rng(ss).random(P.shape) < P
                    indeg[a, b, q, c0:c1] = draws.sum(axis=1)

    return dict(
        indegrees=indeg, d0_list=d0_list, beta_list=beta_list, p0_list=p0_list,
        L_um=np.float64(L_um), rho_per_mm2=np.float64(rho), rep=np.int64(rep),
        N=np.int64(N), boundary=np.str_(boundary), master_seed=np.int64(master),
    )


def task_outfile(out_dir, task):
    boundary, _L_idx, L_um, rep = task
    return os.path.join(out_dir, f"net_{boundary}_L{int(round(L_um))}_rep{rep}.npz")


def worker(task, cfg, out_dir):
    """Top-level (picklable) worker: compute one task and write its file atomically."""
    out = task_outfile(out_dir, task)
    if os.path.exists(out):
        return ("skip", out, 0.0)
    t0 = time.time()
    payload = compute_task(task, cfg)
    # np.savez_compressed appends ".npz"; write to a temp base then atomic-rename.
    tmp_base = out[:-4] + f".tmp.{os.getpid()}"      # strip ".npz"
    np.savez_compressed(tmp_base, **payload)
    os.replace(tmp_base + ".npz", out)
    return ("done", out, time.time() - t0)


# -----------------------------------------------------------------------------
# Task enumeration, cost estimate, sharding
# -----------------------------------------------------------------------------
def build_tasks(cfg):
    tasks = []
    for boundary in cfg["boundaries"]:
        for L_idx, L_um in enumerate(cfg["L_list_um"]):
            for rep in range(cfg["n_rep"]):
                tasks.append((boundary, L_idx, float(L_um), rep))
    return tasks


def estimated_cost(task, cfg):
    """Rough relative cost for longest-processing-time-first scheduling. With
    minimum-image, finite and periodic cost the same (~ N^2 per kernel cell)."""
    _boundary, _L_idx, L_um, _rep = task
    N = n_neurons(L_um, cfg["rho_per_mm2"])
    return (N ** 2) * len(cfg["d0_list"]) * len(cfg["beta_list"])


def detect_n_workers(requested):
    if requested and requested > 0:
        return requested
    try:
        return max(1, len(os.sched_getaffinity(0)))   # respects CPU pinning
    except AttributeError:
        return max(1, os.cpu_count() or 1)


# -----------------------------------------------------------------------------
# CLI / main
# -----------------------------------------------------------------------------
def parse_args(argv=None):
    p = argparse.ArgumentParser(
        description="STEP 1: generate in-degree distributions for the convergence study.")
    p.add_argument("--out_dir", required=True)
    p.add_argument("--rho_per_mm2", type=float, default=2000.0)
    p.add_argument("--L_list_um", type=float, nargs="+",
                   default=[100, 200, 300, 500, 750, 1000, 1500, 2000])
    p.add_argument("--d0_list", type=float, nargs="+",
                   default=[20, 40, 60, 100, 150, 200])
    p.add_argument("--beta_list", type=float, nargs="+",
                   default=[0.2, 0.4, 0.6, 0.8, 1.0])
    p.add_argument("--p0_list", type=float, nargs="+",
                   default=[0.05, 0.1, 0.2, 0.5, 1.0])
    p.add_argument("--boundaries", nargs="+", default=["finite", "periodic"],
                   choices=["finite", "periodic"])
    p.add_argument("--n_rep", type=int, default=20)
    p.add_argument("--chunk", type=int, default=512,
                   help="post-neuron block size (memory/speed trade-off)")
    p.add_argument("--master_seed", type=int, default=20240517)
    p.add_argument("--n_workers", type=int, default=0,
                   help="0 => all CPUs the job is pinned to")
    p.add_argument("--shard", type=int, default=0)
    p.add_argument("--n_shards", type=int, default=1)
    p.add_argument("--dry_run", action="store_true",
                   help="enumerate tasks + cost, write run_config.json, do not compute")
    return p.parse_args(argv)


def main(argv=None):
    args = parse_args(argv)
    os.makedirs(args.out_dir, exist_ok=True)

    cfg = dict(
        rho_per_mm2=args.rho_per_mm2, L_list_um=list(args.L_list_um),
        d0_list=list(args.d0_list), beta_list=list(args.beta_list),
        p0_list=list(args.p0_list), boundaries=list(args.boundaries),
        n_rep=args.n_rep, chunk=args.chunk, master_seed=args.master_seed,
    )

    tasks = build_tasks(cfg)
    tasks.sort(key=lambda t: estimated_cost(t, cfg), reverse=True)   # whales first
    shard_tasks = tasks[args.shard::args.n_shards]

    with open(os.path.join(args.out_dir, "run_config.json"), "w") as fh:
        json.dump(dict(cfg=cfg, n_tasks_total=len(tasks),
                       n_tasks_this_shard=len(shard_tasks),
                       shard=args.shard, n_shards=args.n_shards), fh, indent=2)

    n_workers = detect_n_workers(args.n_workers)
    print(f"[gen] tasks total={len(tasks)}  this shard={len(shard_tasks)}  "
          f"workers={n_workers}  out_dir={args.out_dir}", flush=True)

    if args.dry_run:
        for t in shard_tasks[:10]:
            print(f"  task={t}  est_cost={estimated_cost(t, cfg):.3e}", flush=True)
        print("[gen] dry run only; exiting.", flush=True)
        return

    t_start = time.time()
    done = skipped = 0
    with ProcessPoolExecutor(max_workers=n_workers) as ex:
        futs = {ex.submit(worker, t, cfg, args.out_dir): t for t in shard_tasks}
        for fut in as_completed(futs):
            status, out, dt = fut.result()
            if status == "skip":
                skipped += 1
            else:
                done += 1
                print(f"[gen] done {os.path.basename(out)}  {dt:6.1f}s  "
                      f"({done}/{len(shard_tasks)})", flush=True)

    print(f"[gen] finished: {done} computed, {skipped} skipped, "
          f"{time.time() - t_start:.1f}s wall.", flush=True)


if __name__ == "__main__":
    main()
