# -*- coding: utf-8 -*-
"""Inverse_Transform_function.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TRqK6P5UmE7-oErU-7KuE66nxA1dWyHE
"""

!pip -q install brian2

#!/usr/bin/env python3
# =============================================================================
# colab_async_release_cpp.py
#
# Minimal, self-contained reproduction of the ASYNCHRONOUS-RELEASE synapse
# model on the Brian2 `cpp_standalone` backend, run with BOTH Binomial
# samplers so they can be compared head-to-head on the real C++ code path:
#
#     FORMER  -- Bernoulli-sum loop:  k = sum_{i=1..n} 1[rand() < p]
#                (n rand() draws per call; returns int)   <- the original
#     BINV    -- inverse-transform sampling on the Binomial CDF
#                (exactly ONE rand() draw per call; returns double) <- the new one
#
# Both are EXACT samplers of Binomial(n, p); they differ only in algorithm and
# in how many uniform draws they consume. This script demonstrates, on the
# compiled standalone binary, that:
#   (A) at the sampler level, each reproduces scipy.stats.binom(n, p);
#   (B) at the network level, the two produce statistically indistinguishable
#       ensemble distributions of the history-integrating observables
#       C_async(T) and  integral_0^T Y_S(t) dt.
#
# SCOPE NOTE -----------------------------------------------------------------
# "The network as it is" is reduced here to the synaptic subsystem that the
# Binomial sampler actually lives in (presynaptic Poisson drive -> async +
# synchronous release -> fast cleft glutamate Y_S). The neuronal CAdEx layer,
# the astrocyte/IP3 layer, gliotransmission, and the spatial topology are NOT
# included: they sit downstream of Y_S and are irrelevant to whether the two
# samplers agree. If you want the full neuron+astrocyte network ported to
# Colab instead, say so and I will extend this.
#
# USAGE (Google Colab) -------------------------------------------------------
#   Cell 1:  !pip -q install brian2
#   Cell 2:  paste this file (or  %run colab_async_release_cpp.py)
# Colab ships g++, so cpp_standalone compiles out of the box.
#
# USAGE (CLI) ----------------------------------------------------------------
#   python colab_async_release_cpp.py            # full check, default sizes
#   python colab_async_release_cpp.py --Nsyn 500 --T 5.0 --M 50000
# =============================================================================

# ----------------------------------------------------------------- install ---
# (no-op outside Colab if brian2 is already importable)
try:
    import brian2  # noqa: F401
except ImportError:                       # pragma: no cover
    import subprocess, sys
    subprocess.run([sys.executable, "-m", "pip", "install", "-q", "brian2"],
                   check=True)

import argparse
import sys
import numpy as np
from scipy import stats
from scipy.integrate import trapezoid     # version-agnostic (np.trapz removed in numpy 2.x)
import matplotlib.pyplot as plt


# =============================================================================
# 1. PARAMETERS  (library nominal values; one place, no magic numbers below)
# =============================================================================
PARAMS = dict(
    # --- async / synchronous release ---
    x0          = 0.2,        # quantal vesicle fraction  -> n_max = floor(1/x0) = 5
    Omega_d     = 2.0,        # [1/s]  resource recovery rate
    Omega_f_ar  = 1.42857,    # [1/s]  async facilitation decay (= 1/0.7 s)
    Omega_f_sr  = 2.0,        # [1/s]  sync  facilitation decay
    U_0_ar      = 0.003,      # [-]    async release-prob increment per spike
    U_0_sr      = 0.15,       # [-]    sync  release-prob increment per spike
    Umax        = 500.0,      # [1/s]  ceiling on async rate variable uar
    # --- fast cleft glutamate ---
    Omega_c     = 500.0,      # [1/s]  cleft clearance  -> tau_clear = 2 ms
    rho         = 0.005,      # [-]    vesicle / extracellular volume ratio
    Y_T_mmole   = 6000.0,     # [mmole] total releasable resource (12 ves x 500 mM)
    # --- drive / integration ---
    rate_hz     = 15.0,       # [Hz]   presynaptic Poisson rate per synapse
    dt_ms       = 0.05,       # [ms]   integration step
)


# =============================================================================
# 2. THE TWO SAMPLERS  (python fallback + cython + cpp registrations)
# =============================================================================
# --- FORMER: Bernoulli-sum loop (original). n rand() draws, returns int. ------
FORMER_CPP = r'''
int Binomial_fun(int n, double p, int _vectorisation_idx) {
    int count = 0;
    for (int i = 0; i < n; ++i) {
        if (rand(_vectorisation_idx) < p) count += 1;   // n rand() per call
    }
    return count;
}
'''
FORMER_CYTHON = r'''
cdef double Binomial_fun(int n, double p, _vectorisation_idx):
    cdef int count = 0
    cdef int i
    for i in range(n):
        if rand(_vectorisation_idx) < p:
            count = count + 1
    return count
'''
def _former_py(n, p, _vi):
    return int(np.sum(np.random.rand(int(n)) < p))


# --- BINV: inverse-transform on the Binomial CDF (new). ONE rand(), double. ---
# Walk the pmf recurrence  pmf_{k+1} = pmf_k * (n-k)/(k+1) * p/(1-p),
# accumulating the cdf, and return the first k whose cdf exceeds U ~ Uniform(0,1).
# q^n is built with a short loop (n <= 5) so no <cmath>/pow is pulled in.
BINV_CPP = r'''
double Binomial_fun(int n, double p, int _vectorisation_idx) {
    if (n <= 0 || p <= 0.0) return 0.0;
    if (p >= 1.0) return (double)n;
    double q = 1.0 - p;
    double r = p / q;
    double pmf = 1.0;
    for (int i = 0; i < n; ++i) pmf *= q;       // q^n
    double cdf = pmf;
    double U = rand(_vectorisation_idx);         // exactly ONE draw
    int k = 0;
    while (U > cdf && k < n) {
        k += 1;
        pmf *= ((double)(n - k + 1) / (double)k) * r;
        cdf += pmf;
    }
    return (double)k;
}
'''
BINV_CYTHON = r'''
cdef double Binomial_fun(int n, double p, _vectorisation_idx):
    cdef double q, r, pmf, cdf, U
    cdef int k, i
    if n <= 0 or p <= 0.0:
        return 0.0
    if p >= 1.0:
        return <double>n
    q = 1.0 - p
    r = p / q
    pmf = 1.0
    for i in range(n):
        pmf = pmf * q
    cdf = pmf
    U = rand(_vectorisation_idx)
    k = 0
    while U > cdf and k < n:
        k = k + 1
        pmf = pmf * (<double>(n - k + 1) / <double>k) * r
        cdf = cdf + pmf
    return <double>k
'''
def _binv_py(n, p, _vi):
    n = int(n)
    if n <= 0 or p <= 0.0:
        return 0
    if p >= 1.0:
        return n
    q = 1.0 - p; r = p / q; pmf = q ** n; cdf = pmf; U = np.random.rand(); k = 0
    while U > cdf and k < n:
        k += 1; pmf *= ((n - k + 1) / k) * r; cdf += pmf
    return k


def make_binomial_fun(kind):
    """Build a Brian2 Function 'Binomial_fun' for the chosen sampler.

    kind : 'former' or 'binv'. Registers python (fallback) + cython + cpp,
    so the same object works for target='numpy'/'cython'/'cpp_standalone'.
    """
    from brian2 import Function, DEFAULT_FUNCTIONS
    if kind == 'former':
        py, cy, cpp = _former_py, FORMER_CYTHON, FORMER_CPP
    elif kind == 'binv':
        py, cy, cpp = _binv_py, BINV_CYTHON, BINV_CPP
    else:
        raise ValueError(f"kind must be 'former' or 'binv', got {kind!r}")
    fun = Function(py, arg_units=[1, 1], return_unit=1,
                   stateless=False, auto_vectorise=True)
    dep = {'rand': DEFAULT_FUNCTIONS['rand']}
    fun.implementations.add_implementation('cython', cy, dependencies=dep)
    fun.implementations.add_implementation('cpp',    cpp, dependencies=dep)
    return fun


def _fresh_cpp_device(build_dir):
    """Activate a clean cpp_standalone device (needed between sequential runs)."""
    from brian2 import set_device, get_device
    set_device('cpp_standalone', directory=build_dir, build_on_run=True)
    get_device().reinit()
    get_device().activate(build_on_run=True, directory=build_dir)


# =============================================================================
# 3. PART A -- sampler unit test on cpp_standalone vs scipy.stats.binom
# =============================================================================
def nominal_grid(P):
    """The (n, p) grid the production smoke test uses."""
    n_max = int(np.floor(1.0 / P['x0']))                 # 5
    p_max = P['Umax'] * (P['dt_ms'] * 1e-3)              # 0.025
    ns = sorted(set(max(1, int(round(v))) for v in np.linspace(1, n_max, 4)))
    ps = [p_max / 50.0, p_max / 10.0, p_max / 2.0, p_max]
    return [(n, float(p)) for n in ns for p in ps]


def sampler_check(kind, P, M, seed, build_dir):
    """Draw M samples per (n,p) cell on cpp_standalone; KS/moment-test vs scipy."""
    from brian2 import (start_scope, NeuronGroup, StateMonitor, run,
                        defaultclock, ms, seed as bseed)
    _fresh_cpp_device(build_dir)
    start_scope()
    defaultclock.dt = P['dt_ms'] * ms

    fun = make_binomial_fun(kind)
    grid = nominal_grid(P)
    n_arr = np.array([g[0] for g in grid], float)
    p_arr = np.array([g[1] for g in grid], float)

    G = NeuronGroup(
        len(grid),
        '''n_cell : 1 (constant)
           p_cell : 1 (constant)
           k = Binomial_fun(int(n_cell), p_cell) : 1 (constant over dt)''',
        namespace={'Binomial_fun': fun},
    )
    G.n_cell = n_arr; G.p_cell = p_arr
    mon = StateMonitor(G, 'k', record=True, dt=P['dt_ms'] * ms)
    bseed(seed)
    run(M * P['dt_ms'] * ms)                              # M steps -> M samples/cell
    K = np.asarray(mon.k)                                 # (ncells, ~M)

    print(f"\n--- PART A: {kind.upper()} sampler on cpp_standalone "
          f"(M={K.shape[1]}/cell) ---")
    print(f"{'n':>2} {'p':>9} | {'np':>7} {'mean':>8} | {'npq':>7} {'var':>8}"
          f" | {'var/npq':>7} | {'KS_p':>8}  res")
    all_ok = True
    for c, (n, p) in enumerate(grid):
        s = K[c]; q = 1.0 - p
        mean_th, var_th = n * p, n * p * q
        ref = stats.binom.rvs(n, p, size=s.size, random_state=seed + c)
        ks, pv = stats.ks_2samp(s, ref)
        ratio = s.var() / var_th if var_th > 0 else np.nan
        ok = pv > 1e-4
        all_ok &= ok
        print(f"{n:>2} {p:>9.2e} | {mean_th:>7.4f} {s.mean():>8.4f} | "
              f"{var_th:>7.4f} {s.var():>8.4f} | {ratio:>7.2f} | "
              f"{pv:>8.2g}  {'OK' if ok else 'FAIL'}")
    print(f"PART A {kind.upper()}: {'PASS' if all_ok else 'FAIL'}")
    return all_ok


# =============================================================================
# 4. PART B -- async-release network on cpp_standalone
# =============================================================================
def make_poisson_drive(Nsyn, T_s, rate_hz, dt_s, seed):
    """Pre-generate per-synapse Poisson spike trains on the dt grid.

    Returned once and reused for BOTH samplers, so the drive is byte-identical
    across runs and the only difference is the Binomial algorithm itself.
    """
    rng = np.random.default_rng(seed)
    nsteps = int(round(T_s / dt_s))
    idx, t = [], []
    for j in range(Nsyn):
        hits = np.nonzero(rng.random(nsteps) < rate_hz * dt_s)[0]
        idx.append(np.full(hits.size, j)); t.append(hits * dt_s)
    idx = np.concatenate(idx); t = np.concatenate(t)
    order = np.argsort(t, kind='stable')                 # SpikeGeneratorGroup wants sorted t
    return idx[order], t[order]


def run_async_network(kind, drive, P, Nsyn, T_s, seed, build_dir, n_trace=6):
    """Build + run the async-release synapse model on cpp_standalone.

    Observables (both integrate history, hence endpoint-robust):
      C_async(T)  -- cumulative async-released NT (dimensionless)
      YS_int(T)   -- integral_0^T Y_S dt          (mole*second), in-equation integrator
    A few Y_S(t) traces are also recorded for plotting and as an integrator cross-check.
    """
    from brian2 import (start_scope, NeuronGroup, Synapses, SpikeGeneratorGroup,
                        StateMonitor, run, defaultclock, ms, second, Hz,
                        mmole, mole, seed as bseed)
    spk_i, spk_t = drive
    _fresh_cpp_device(build_dir)
    start_scope()
    defaultclock.dt = P['dt_ms'] * ms

    Binomial_fun = make_binomial_fun(kind)
    ns = {'Omega_c': P['Omega_c'] / second, 'rho': P['rho'],
          'Binomial_fun': Binomial_fun}

    # ---- async + synchronous release + fast cleft Y_S (library equations) ----
    eqs = '''
    dx_S/dt = Omega_d*(1 - x_S) - r_Ar                    : 1    (clock-driven)
    r_Ar    = x0*nar                                       : Hz
    nar     = Binomial_fun(int(floor(x_S/x0)), uar*dt)/dt : Hz   (constant over dt)
    duar/dt = -uar*Omega_f_ar                             : Hz   (clock-driven)
    dusr/dt = -Omega_f_sr*usr                             : 1    (clock-driven)
    r_Sr : 1
    dY_S/dt     = -Omega_c*Y_S + rho*Y_T*r_Ar             : mole (clock-driven)
    dC_async/dt = r_Ar                                    : 1    (clock-driven)
    dYS_int/dt  = Y_S                                     : mole*second (clock-driven)
    Omega_d : 1/second
    Omega_f_ar : 1/second
    Omega_f_sr : 1/second
    U_0_ar : 1
    U_0_sr : 1
    Umax : 1/second
    x0 : 1
    Y_T : mole
    '''
    on_pre = '''
    usr += U_0_sr*(1 - usr)
    r_Sr = usr*x_S
    x_S -= r_Sr
    uar += U_0_ar*(Umax - uar)
    Y_S += rho*Y_T*r_Sr
    '''
    P_in = SpikeGeneratorGroup(Nsyn, spk_i, spk_t * second)
    post = NeuronGroup(Nsyn, 'dummy : 1')
    S = Synapses(P_in, post, model=eqs, on_pre=on_pre, namespace=ns, method='euler')
    S.connect(j='i')                                      # one synapse per drive line

    # initial conditions + per-synapse parameters (library nominal)
    S.x_S = 1.0; S.usr = 0.0; S.uar = 0.0 * Hz; S.Y_S = 0.0 * mmole
    S.C_async = 0.0; S.YS_int = 0.0 * mole * second
    S.Omega_d    = P['Omega_d']    / second
    S.Omega_f_ar = P['Omega_f_ar'] / second
    S.Omega_f_sr = P['Omega_f_sr'] / second
    S.U_0_ar = P['U_0_ar']; S.U_0_sr = P['U_0_sr']
    S.Umax = P['Umax'] / second
    S.x0 = P['x0']; S.Y_T = P['Y_T_mmole'] * mmole

    # record a few synapses' Y_S(t) for plotting + integrator cross-check
    rec = np.arange(min(n_trace, Nsyn))
    monYS = StateMonitor(S, 'Y_S', record=rec, dt=P['dt_ms'] * ms)

    bseed(seed)
    run(T_s * second)

    C     = np.asarray(S.C_async[:])
    YSint = np.asarray(S.YS_int[:] / (mole * second))
    YS_tr = np.asarray(monYS.Y_S / mmole)                 # (n_trace, nsteps) in mmole
    tgrid = np.asarray(monYS.t / second)
    # cross-check the in-equation integrator against an offline trapezoid (mole*s)
    off = trapezoid(YS_tr * 1e-3, tgrid, axis=1)
    xchk = float(np.max(np.abs(YSint[rec] - off)))
    nz_final = int(np.sum(np.asarray(S.Y_S[:] / mmole) > 0))
    return dict(C=C, YSint=YSint, YS_tr=YS_tr, tgrid=tgrid,
                xchk=xchk, nz_final=nz_final)


def compare_ensembles(rF, rB, Nsyn):
    """KS-test the FORMER vs BINV ensemble distributions of each observable."""
    print(f"\n--- PART B: async network on cpp_standalone, "
          f"FORMER vs BINV over {Nsyn} synapses ---")
    out = {}
    for name, a, b in [("C_async(T)", rF['C'], rB['C']),
                       ("int Y_S dt", rF['YSint'], rB['YSint'])]:
        ks, pv = stats.ks_2samp(a, b)
        ok = pv > 1e-3
        out[name] = ok
        print(f"  {name:<11s}: FORMER mean={a.mean():.4g} std={a.std():.3g} | "
              f"BINV mean={b.mean():.4g} std={b.std():.3g} | "
              f"KS p={pv:.3f}  {'PASS' if ok else 'FAIL'}")
    print(f"  in-equation int Y_S dt vs offline trapezoid: "
          f"FORMER max|d|={rF['xchk']:.1e}, BINV max|d|={rB['xchk']:.1e}")
    print(f"  Y_S(T) nonzero at endpoint (the DEGENERATE observable to avoid): "
          f"FORMER {rF['nz_final']}/{Nsyn}, BINV {rB['nz_final']}/{Nsyn}")
    print(f"PART B: {'PASS' if all(out.values()) else 'FAIL'}")
    return all(out.values())


# =============================================================================
# 5. PLOTS
# =============================================================================
def make_plots(rF, rB, out_png="async_release_cpp.png"):
    fig, ax = plt.subplots(1, 3, figsize=(15, 4.2))
    # (a) C_async(T) histograms
    bins = np.histogram_bin_edges(np.concatenate([rF['C'], rB['C']]), bins=30)
    ax[0].hist(rF['C'], bins=bins, alpha=0.55, label='FORMER', color='#1f4e79')
    ax[0].hist(rB['C'], bins=bins, alpha=0.55, label='BINV',   color='#c0504d')
    ax[0].set_xlabel(r'$C_\mathrm{async}(T)$  (cumulative released NT)')
    ax[0].set_ylabel('synapse count'); ax[0].set_title('(a) cumulative async release')
    ax[0].legend(frameon=False)
    # (b) int Y_S dt histograms
    bins = np.histogram_bin_edges(np.concatenate([rF['YSint'], rB['YSint']]), bins=30)
    ax[1].hist(rF['YSint'], bins=bins, alpha=0.55, label='FORMER', color='#1f4e79')
    ax[1].hist(rB['YSint'], bins=bins, alpha=0.55, label='BINV',   color='#c0504d')
    ax[1].set_xlabel(r'$\int_0^T Y_S\,dt$  (mole$\cdot$s)')
    ax[1].set_ylabel('synapse count'); ax[1].set_title('(b) cleft-glutamate exposure')
    ax[1].legend(frameon=False)
    # (c) example Y_S(t) traces
    for k in range(min(3, rB['YS_tr'].shape[0])):
        ax[2].plot(rB['tgrid'], rB['YS_tr'][k], lw=0.8)
    ax[2].set_xlabel('time (s)'); ax[2].set_ylabel(r'$Y_S$ (mmole)')
    ax[2].set_title(r'(c) example $Y_S(t)$ traces (BINV)')
    fig.tight_layout()
    fig.savefig(out_png, dpi=130)
    print(f"\n[plot] saved -> {out_png}")
    try:
        plt.show()
    except Exception:
        pass


# =============================================================================
# 6. MAIN
# =============================================================================
def _in_notebook():
    """True when running inside an IPython/Jupyter/Colab kernel."""
    try:
        from IPython import get_ipython
        ip = get_ipython()
        return ip is not None and ip.__class__.__name__ != 'TerminalInteractiveShell'
    except Exception:
        return False


def main(argv=None):
    # In Colab/Jupyter, sys.argv carries the kernel's own flags
    # (e.g. "-f .../kernel.json"); ignore them and use defaults there.
    if argv is None:
        argv = [] if _in_notebook() else sys.argv[1:]

    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--Nsyn', type=int, default=200, help='synapses in PART B')
    ap.add_argument('--T',    type=float, default=5.0, help='sim time [s] in PART B')
    ap.add_argument('--M',    type=int, default=20000, help='samples/cell in PART A')
    ap.add_argument('--seed', type=int, default=1234)
    ap.add_argument('--skipA', action='store_true', help='skip the sampler unit test')
    ap.add_argument('--skipB', action='store_true', help='skip the network test')
    ap.add_argument('--noplot', action='store_true')
    args, _unknown = ap.parse_known_args(argv)
    P = PARAMS

    print("=" * 70)
    print("async-release on cpp_standalone | FORMER vs BINV Binomial samplers")
    print(f"x0={P['x0']}  n_max={int(1/P['x0'])}  Omega_c={P['Omega_c']}Hz "
          f"(tau_clear={1e3/P['Omega_c']:.1f} ms)  rho={P['rho']}  "
          f"Y_T={P['Y_T_mmole']} mmole")
    print(f"dt={P['dt_ms']} ms  rate={P['rate_hz']} Hz  "
          f"PART A M={args.M}  PART B Nsyn={args.Nsyn} T={args.T}s  seed={args.seed}")
    print("=" * 70)

    okA = True
    if not args.skipA:
        okA_f = sampler_check('former', P, args.M, args.seed, '/tmp/sampA_former')
        okA_b = sampler_check('binv',   P, args.M, args.seed, '/tmp/sampA_binv')
        okA = okA_f and okA_b

    okB = True
    rF = rB = None
    if not args.skipB:
        dt_s = P['dt_ms'] * 1e-3
        drive = make_poisson_drive(args.Nsyn, args.T, P['rate_hz'], dt_s, args.seed)
        print(f"\n[drive] Nsyn={args.Nsyn}  total presyn spikes={drive[0].size}")
        rF = run_async_network('former', drive, P, args.Nsyn, args.T,
                               args.seed, '/tmp/netB_former')
        rB = run_async_network('binv',   drive, P, args.Nsyn, args.T,
                               args.seed, '/tmp/netB_binv')
        okB = compare_ensembles(rF, rB, args.Nsyn)
        if not args.noplot:
            make_plots(rF, rB)

    print("\n" + "=" * 70)
    print(f"OVERALL: PART A {'PASS' if okA else 'FAIL'} | "
          f"PART B {'PASS' if okB else 'FAIL'} | "
          f"{'ALL PASS' if (okA and okB) else 'SOME FAILED'}")
    print("=" * 70)
    return 0 if (okA and okB) else 1


if __name__ == '__main__':
    _rc = main()
    if not _in_notebook():
        raise SystemExit(_rc)